# Generated by Django 5.2.10 on 2026-01-26 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('total_er_rooms', models.IntegerField()),
                ('occupied_er_rooms', models.IntegerField(default=0)),
                ('icu_beds_available', models.IntegerField(default=0)),
                ('cardiologist_available', models.BooleanField(default=False)),
                ('neurosurgeon_available', models.BooleanField(default=False)),
                ('trauma_team_available', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_type', models.CharField(choices=[('cardiac', 'Cardiac'), ('trauma', 'Trauma'), ('neuro', 'Neuro'), ('general', 'General')], max_length=20)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('selected_hospital', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.hospital')),
            ],
        ),
    ]
