# Generated by Django 5.2.10 on 2026-01-26 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emergencycase',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='emergencycase',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='longitude',
        ),
        migrations.AddField(
            model_name='emergencycase',
            name='ambulance_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emergencycase',
            name='patient_type',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='TrafficInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travel_time_minutes', models.FloatField()),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.emergencycase')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.hospital')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ambulance', 'Ambulance Driver'), ('hospital', 'Hospital Staff')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
