# Generated by Django 5.2.10 on 2026-01-26 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_emergencycase_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='total_er_rooms',
            field=models.IntegerField(default=0),
        ),
    ]
