# Generated by Django 5.2.10 on 2026-01-26 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_hospital_last_updated_alter_hospital_total_er_rooms'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospital',
            old_name='occupied_er_rooms',
            new_name='er_rooms_available',
        ),
    ]
