# Generated by Django 5.2.10 on 2026-01-26 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_occupied_er_rooms_hospital_er_rooms_available'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='emergencycase',
            name='patient_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='emergencycase',
            name='selected_hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.hospital'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('ambulance', 'Ambulance Driver'), ('hospital', 'Hospital')], max_length=20),
        ),
    ]
