# Generated by Django 5.2.10 on 2026-03-04 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_hospital_latitude_hospital_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='total_er_rooms',
        ),
        migrations.AlterField(
            model_name='hospital',
            name='er_rooms_available',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='icu_beds_available',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
