# Generated by Django 5.2.10 on 2026-03-04 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_hospital_total_er_rooms_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('ambulance', 'Ambulance Driver'), ('hospital', 'Hospital'), ('citizen', 'Common User')], max_length=20),
        ),
        migrations.CreateModel(
            name='HealthProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('blood_group', models.CharField(max_length=5)),
                ('diabetes', models.BooleanField(default=False)),
                ('heart_disease', models.BooleanField(default=False)),
                ('allergies', models.TextField(blank=True)),
                ('emergency_contact', models.CharField(max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
