# Generated by Django 5.2.10 on 2026-03-04 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_userprofile_role_healthprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='healthprofile',
            old_name='allergies',
            new_name='comments',
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='aadhar_number',
            field=models.CharField(default=0, max_length=12, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='name',
            field=models.CharField(default=123412341234, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='healthprofile',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='healthprofile',
            name='blood_group',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='healthprofile',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='er_rooms_available',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='icu_beds_available',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('ambulance', 'Ambulance Driver'), ('hospital', 'Hospital'), ('citizen', 'Common Citizen')], max_length=20),
        ),
    ]
