# Generated by Django 5.2.10 on 2026-03-04 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_patienttransfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='patienttransfer',
            name='eta_minutes',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
