# Generated by Django 5.2.10 on 2026-03-04 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_patienttransfer_eta_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='patienttransfer',
            name='patient_type',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
