# Generated by Django 5.2.10 on 2026-03-04 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_distresssignal'),
    ]

    operations = [
        migrations.AddField(
            model_name='distresssignal',
            name='emergency_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
