# Generated by Django 5.2.10 on 2026-03-04 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_distresssignal_emergency_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='location_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
